# -*- coding: utf-8 -*-
"""
agents.py — AgenticPD multi-agent definitions (paper-aligned version)

Corresponds to paper §4-§6:
1. ObservationTool: E(n) exploration balance + B(s) stage bottleneck → adaptive summary
2. BaseAgent: template method act = build prompt → call LLM → validate
3. JudgeAgent: select branch node n_hat and branch stage b from tree,
   generate hints for {b}∪Aft(b)
4. StageAgent and FP/PL/CTS/RT subclasses: receive upstream QoR from current
   branch + cross-iteration experience + Judge hint
"""

from __future__ import annotations

import abc
import logging
from typing import Any, Dict, List, Optional, Tuple

import config
from config import FrameworkConfig, ParamSpec
from llm_interface import LLMError

log = logging.getLogger("agents")

STAGE_CN: Dict[str, str] = {
    "FP": "Floorplan",
    "PL": "Standard Cell Placement",
    "CTS": "Clock Tree Synthesis",
    "RT": "Routing",
}


# =========================================================================
# Observation Tool (paper §4.2): tree + history → adaptive summary
# =========================================================================

def compute_exploration_balance(tree, max_branch_count: int) -> Dict[str, int]:
    """E(n): number of times each branchable node was chosen as branch origin"""
    nodes = tree.branchable_nodes(max_branch_count)
    return {n.node_id: n.branch_count for n in nodes}


def compute_stage_bottleneck(history: List[Dict[str, Any]],
                              best_qor) -> Dict[str, float]:
    """B(s): difference between best observed intermediate ws (ps) per stage
    across non-failed history entries and the global best ws.

    difference = best_ws - stage_best_ws (positive = this stage is the bottleneck).
    Returns 0 if no data for a stage.
    """
    from utils import QoR
    scores: Dict[str, List[float]] = {s: [] for s in config.STAGES}
    for entry in history:
        if entry.get("status") != "ok":
            continue
        sq = entry.get("stage_qor", {})
        for stage in config.STAGES:
            sqs = sq.get(stage, {})
            for key, val in sqs.items():
                if key.endswith("_ws_ps"):
                    scores[stage].append(float(val))
    best_ws = best_qor.wns_ps if best_qor and best_qor.wns_ps is not None else 0.0
    result: Dict[str, float] = {}
    for stage in config.STAGES:
        vals = scores[stage]
        if not vals:
            result[stage] = 0.0
        else:
            result[stage] = round(best_ws - max(vals), 1)
    return result


def build_observation_summary(tree, history: List[Dict[str, Any]],
                               best_qor, max_branch_count: int) -> str:
    """Build the "adaptive summary" text block for the Judge.

    Contains:
    - Branchable node list (node_id / stage / E(n) / per-stage ws along path)
    - Per-stage bottleneck scores B(s)
    """
    parts = ["## Search State Summary (auto-generated by Observation Tool)"]

    # Branchable node table
    nodes = tree.branchable_nodes(max_branch_count)
    if nodes:
        parts += ["\n### Branchable Nodes (selecting one reuses Bef results, zero re-run cost)",
                  "| node_id | stage | E(n) | Path QoR (ws_ps) |",
                  "|---------|-------|------|-----------------|"]
        for n in nodes:
            path_qor = tree.get_path_qor_summary(n.node_id)
            qor_str = " → ".join(
                f"{s}:{ws:.0f}" if ws is not None else f"{s}:?" for s, ws in path_qor)
            parts.append(f"| {n.node_id} | {n.stage} | {n.branch_count} | {qor_str} |")
    else:
        parts += ["\n(No branchable nodes — this round must start from ROOT, full run from FP)"]

    # Stage bottleneck scores
    bottleneck = compute_stage_bottleneck(history, best_qor)
    parts += ["\n### Stage Bottleneck B(s) (ws gap vs. global best; larger positive = more bottlenecked)"]
    for stage in config.STAGES:
        parts.append(f"- {stage} ({STAGE_CN[stage]}): B={bottleneck[stage]:.1f} ps")
    if best_qor is not None:
        parts.append(f"\nGlobal best ws (reference baseline): {best_qor.wns_ps:.1f} ps")

    return "\n".join(parts)


# =========================================================================
# History serialization (shared by Judge and StageAgent)
# =========================================================================

def _format_params_inline(stage_params: Dict[str, Dict[str, Any]]) -> str:
    parts = []
    for stage in config.STAGES:
        params = stage_params.get(stage, {})
        inner = ",".join(f"{k}:{v}" for k, v in params.items())
        parts.append(f"{stage}{{{inner}}}")
    return " ".join(parts)


def _format_entry_line(entry: Dict[str, Any], is_best: bool) -> str:
    """Single history entry → one-line text (including branch info)"""
    it = entry.get("iteration")
    params_str = _format_params_inline(entry.get("params", {}))

    branch_info = ""
    bn = entry.get("branch_node")
    bs = entry.get("branch_stage")
    if bn and bs:
        # Show only meaningful fragments to avoid excessively long lines:
        # extract iter number and stage
        short_node = bn.split("_")[-2] + "_" + bn.split("_")[-1] if "_" in bn else bn
        branch_info = f", from {short_node}@{bs}"

    if entry.get("status") == "ok" and entry.get("qor"):
        from utils import QoR
        qor = QoR.from_dict(entry["qor"])
        status_str = "[ok" + branch_info + "]"
        qor_str = qor.pretty() if qor else "QoR=N/A"
    else:
        failed_stage = entry.get("failed_stage") or "unknown"
        status_str = f"[FAILED@{failed_stage}{branch_info}]"
        qor_str = "QoR=N/A"

    line = f"#{it} {status_str} {params_str} | {qor_str}"

    decision = entry.get("judge_decision")
    if decision:
        bs_short = decision.get("branch_stage", "")
        hint = (decision.get("hints", {}).get(bs_short) or
                decision.get("hint") or "")[:50]
        line += f" | judge:{bs_short} \"{hint}\""
    if is_best:
        line += "  *BEST*"
    return line


def format_history(history: List[Dict[str, Any]], window: int,
                   best_iteration: Optional[int]) -> str:
    """Serialize optimization history: take most recent `window` entries,
    always including the best entry (marked *BEST*)"""
    if not history:
        return "(No history yet)"

    recent = history[-window:]
    lines: List[str] = []
    recent_iters = {e.get("iteration") for e in recent}
    if best_iteration is not None and best_iteration not in recent_iters:
        best_entry = next((e for e in history
                           if e.get("iteration") == best_iteration), None)
        if best_entry:
            lines.append(_format_entry_line(best_entry, is_best=True))
            lines.append("...")
    for entry in recent:
        lines.append(_format_entry_line(
            entry, is_best=(entry.get("iteration") == best_iteration)))
    return "\n".join(lines)


def render_param_table(stage: str) -> str:
    lines = []
    for spec in config.PARAM_SPACE[stage]:
        rng = (f"{int(spec.vmin)}–{int(spec.vmax)}" if spec.ptype == "int"
               else f"{spec.vmin}–{spec.vmax}")
        base = "baseline unset" if spec.default is None else f"baseline={spec.default}"
        lines.append(f"- {spec.name} ({spec.ptype}, range {rng}, {base}): {spec.description}")
    return "\n".join(lines)


def default_stage_params(stage: str) -> Dict[str, Any]:
    params = dict(config.BASELINE_PARAMS.get(stage, {}))
    for spec in config.PARAM_SPACE[stage]:
        if spec.name not in params and spec.default is not None:
            params[spec.name] = spec.default
    return params


# =========================================================================
# Agent base class
# =========================================================================

class AgentOutputError(Exception):
    """LLM output parsed as valid JSON but failed business-rule validation"""


class BaseAgent(abc.ABC):
    tag: str = "base"

    def __init__(self, llm: Any, cfg: FrameworkConfig):
        self.llm = llm
        self.cfg = cfg

    @abc.abstractmethod
    def system_prompt(self) -> str: ...

    @abc.abstractmethod
    def build_user_prompt(self, context: Dict[str, Any]) -> str: ...

    @abc.abstractmethod
    def schema_desc(self) -> str: ...

    @abc.abstractmethod
    def validate(self, raw: Dict[str, Any],
                 context: Dict[str, Any]) -> Dict[str, Any]: ...

    def act(self, context: Dict[str, Any]) -> Dict[str, Any]:
        system = self.system_prompt()
        user = self.build_user_prompt(context)
        log.debug("[%s] SYSTEM PROMPT:\n%s", self.tag, system)
        log.debug("[%s] USER PROMPT:\n%s", self.tag, user)
        raw = self.llm.chat_json(
            system=system, user=user,
            schema_desc=self.schema_desc(), tag=self.tag)
        return self.validate(raw, context)


# =========================================================================
# JudgeAgent (paper §4)
# =========================================================================

class JudgeAgent(BaseAgent):
    """Judge: analyzes optimization tree + observation summary, selects branch
    node n_hat and branch stage b_k, and generates a dedicated hint for each
    stage in {b_k} ∪ Aft(b_k)."""

    tag = "judge"

    def system_prompt(self) -> str:
        stage_sections = "\n\n".join(
            f"### {stage} — {STAGE_CN[stage]}\n{render_param_table(stage)}"
            for stage in config.STAGES)
        return f"""You are the QoR optimization controller (Judge Agent) for digital backend physical design.
Target: OpenROAD Flow Scripts full RTL→GDS flow, design {self.cfg.design}, PDK {self.cfg.platform}.

The flow consists of four optimizable stages. Tunable parameters per stage:

{stage_sections}

QoR priority (evaluate in order; move to next only if the current is a tie):
1. WNS (Worst Negative Slack, ps, higher is better, >= 0 means timing met;
   differences < {self.cfg.wns_tol_ps} ps are considered a tie)
2. TNS (Total Negative Slack, ps, higher is better;
   differences < {self.cfg.tns_tol_ps} ps are considered a tie)
3. Power (W, lower is better)
4. Area (µm², lower is better)

## Branching Mechanism (your core capability)

The optimization process is organized as a tree: each completed flow stage (FP/PL/CTS/RT)
leaves a snapshot node for that iteration. You may select any historical node n_hat as the
"branch origin", restarting execution from the stage following n_hat. All Bef stages'
results are reused at zero cost; only {{branch_stage}} ∪ Aft(branch_stage) stages are
re-run. Selecting the root node (ROOT) with branch_stage=FP is equivalent to running a
full flow from scratch.

The "Observation Summary" in your input contains two key signals:
- E(n): how many times this node has been chosen as a branch origin.
  Low count → underexplored, worth trying;
  high count with no improvement → possibly avoid this parameter region;
- B(s): stage bottleneck score = global best ws − best historical ws for this stage.
  The stage with the largest positive B(s) is likely the current bottleneck and should
  be prioritized as branch_stage.

## Your Decision Requirements

Analyze the observation summary + historical trends and choose:
- branch_node: pick a node_id from the branchable node table (or "ROOT" to start fresh)
- branch_stage: the stage at which to start re-running, starting from the chosen node.
  **Consistency constraint**: branch_stage MUST be the stage immediately following
  branch_node's stage (ROOT→FP, FP node→PL, PL node→CTS, CTS node→RT) — choosing a
  node uniquely determines the re-run start point. If you want to start re-running from
  CTS, pick a PL node on some path as branch_node. Inconsistent output will be forcibly
  corrected by the system.
- hints: write one dedicated, specific, actionable tuning hint for each stage in
  {{branch_stage}} ∪ Aft(branch_stage) (which direction to tune, roughly how much, why).
  Bef stages automatically reuse the node's results and need no hints.

Decision principles:
- Avoid re-exploring regions that cannot produce improvements (consider E(n) + FAILED
  markers in history);
- When timing is unmet (WNS < 0), prioritize the most bottlenecked stage; when timing is
  met, consider area/power optimization;
- If multiple consecutive rounds show no improvement, switch stages or restart from an
  earlier node (even back to ROOT for a full re-run).

Output requirements: output ONLY one JSON object, no other text."""

    def build_user_prompt(self, context: Dict[str, Any]) -> str:
        summary = context.get("summary", "(No observation summary available)")
        history: List[Dict[str, Any]] = context.get("history", [])
        best = context.get("best")
        best_iter = best.get("iteration") if best else None

        parts = [summary]
        if best:
            from utils import QoR
            qor = QoR.from_dict(best.get("qor"))
            parts += [
                "\n## Current Best",
                f"Iteration #{best.get('iteration')}: {qor.pretty() if qor else 'N/A'}",
                f"Params: {_format_params_inline(best.get('params', {}))}",
            ]
        parts += [
            f"\n## Recent Optimization History ({len(history)} rounds total)",
            format_history(history, self.cfg.history_window, best_iter),
            "\nPlease provide the next branch decision. JSON format:",
            self.schema_desc(),
        ]
        return "\n".join(parts)

    def schema_desc(self) -> str:
        stages = "|".join(config.STAGES)
        return (
            '{"branch_node": "<ROOT or a node_id from the branchable node table>", '
            f'"branch_stage": "<one of {stages}>", '
            '"hints": {"FP": "<hint for FP>", '
            '"PL": "<hint for PL>", '
            '"CTS": "<hint for CTS>", '
            '"RT": "<hint for RT>"}, '
            '"reason": "<brief justification>"}'
        )

    def validate(self, raw: Dict[str, Any],
                 context: Dict[str, Any]) -> Dict[str, Any]:
        branch_node = str(raw.get("branch_node", "ROOT")).strip()
        branch_stage = str(raw.get("branch_stage", "")).strip().upper()
        if branch_stage not in config.STAGES:
            raise AgentOutputError(f"Invalid branch_stage: {raw.get('branch_stage')!r}")
        hints_in = raw.get("hints")
        hints: Dict[str, str] = {}
        if isinstance(hints_in, dict):
            for stage in config.STAGES:
                hints[stage] = str(hints_in.get(stage, "")).strip()
        else:
            hints = {s: "" for s in config.STAGES}
        return {
            "branch_node": branch_node,
            "branch_stage": branch_stage,
            "hints": hints,
            "reason": str(raw.get("reason", "")).strip(),
        }

    def act(self, context: Dict[str, Any]) -> Dict[str, Any]:
        try:
            try:
                return super().act(context)
            except AgentOutputError as e:
                log.warning("[Judge Agent] invalid output (%s), retrying once", e)
                raw = self.llm.chat_json(
                    system=self.system_prompt(),
                    user=(self.build_user_prompt(context)
                          + f"\n\nNote: your last output was invalid ({e}), "
                            f"branch_stage must be one of {'/'.join(config.STAGES)}."),
                    schema_desc=self.schema_desc(),
                    tag=self.tag)
                return self.validate(raw, context)
        except (LLMError, AgentOutputError) as e:
            n_done = len(context.get("history", []))
            stage = config.STAGES[n_done % len(config.STAGES)]
            log.error("[Judge Agent] fallback (%s): branch from ROOT, choose %s", e, stage)
            return {
                "branch_node": "ROOT",
                "branch_stage": stage,
                "hints": {s: ("(Judge fault, explore with small steps)" if s == stage else "(fallback)")
                          for s in config.STAGES},
                "reason": f"fallback: {e}",
            }


# =========================================================================
# StageAgent (paper §5): receives upstream QoR + cross-iteration experience
# + Judge hint
# =========================================================================

class StageAgent(BaseAgent):
    """Stage parameter generation agent.

    Only invoked when selected (s ∈ {b_k} ∪ Aft(b_k)).
    Context fields (paper §5.1):
        upstream_qor          : QoR of Bef(stage) stages in current branch
                                [{stage, ws_ps, tns_ps}, ...]
        cross_iteration_exp   : historical records where this stage was
                                the branch_stage (cross-iteration experience e_s)
        hint                  : Judge's dedicated hint for this stage
        global_best           : global best entry (reference baseline)
    """

    stage: str = ""
    persona: str = ""

    def __init__(self, llm: Any, cfg: FrameworkConfig):
        super().__init__(llm, cfg)
        assert self.stage in config.STAGES, f"Invalid stage: {self.stage}"
        self.tag = f"stage:{self.stage}"
        self.specs: List[ParamSpec] = config.PARAM_SPACE[self.stage]

    def system_prompt(self) -> str:
        return f"""You are {self.persona}
You are responsible for parameter decisions in the {STAGE_CN[self.stage]} stage of the
OpenROAD flow. Your output only affects this stage's parameter values (Bef stage results
are inherited from the parent branch node and will not be re-run).

Tunable parameters you manage (output ALL of them, strictly within range):
{render_param_table(self.stage)}

Notes:
- Parameter value types must be correct (int params should not have decimals);
- Do not output any parameter not listed above;
- Small-step adjustments are usually safer than large jumps, but you may increase
  step size when stuck.

Output requirements: output ONLY one JSON object, no other text."""

    def build_user_prompt(self, context: Dict[str, Any]) -> str:
        parts: List[str] = []

        # 1) Upstream QoR in this branch (paper ctx_s: {Q_k(i)}_{i∈Bef(s)})
        upstream = context.get("upstream_qor", [])
        if upstream:
            parts += ["## Completed Upstream (Bef) Stage QoR in This Branch",
                      "(These stages' params and results are inherited from the parent "
                      "branch node and will NOT be re-run)"]
            for item in upstream:
                if isinstance(item, dict):
                    parts.append(
                        f"- {item.get('stage', '?')}: ws={item.get('ws_ps', '?')}ps "
                        f"tns={item.get('tns_ps', '?')}ps")
                elif isinstance(item, tuple) and len(item) == 2:
                    parts.append(f"- {item[0]}: ws={item[1]}ps")
                else:
                    parts.append(f"- {item}")
        else:
            parts += ["## Upstream Stages in This Branch",
                      "(You are the first stage to execute in this branch; no upstream QoR)"]

        # 2) Cross-iteration experience e_s (past attempts targeting this stage)
        cross = context.get("cross_iteration_exp", [])
        if cross:
            parts += ["\n## Past Attempts Targeting This Stage (cross-iteration exp e_s)"]
            for entry in cross:
                it = entry.get("iteration", "?")
                params = entry.get("params", {}).get(self.stage, {})
                sq = (entry.get("stage_qor") or {}).get(self.stage, {})
                ws_str = "N/A"
                for k, v in sq.items():
                    if k.endswith("_ws_ps"):
                        ws_str = f"{v:.1f}ps"
                        break
                parts.append(f"  #{it} params={params} ws={ws_str}")
        else:
            parts += ["\n## Past Attempts for This Stage",
                      "(No records yet — start from reasonable conservative values)"]

        # 3) Global best (reference baseline)
        best = context.get("global_best")
        if best:
            from utils import QoR
            qor = QoR.from_dict(best.get("qor"))
            best_my = best.get("params", {}).get(self.stage, {})
            parts += [
                "\n## Global Best (reference baseline)",
                f"Iteration #{best.get('iteration')}: {qor.pretty() if qor else 'N/A'}",
                f"This stage's params in that iteration: {best_my or '(baseline defaults)'}",
            ]

        # 4) Judge hint
        hint = context.get("hint", "")
        parts += ["\n## Judge Hint",
                  hint if hint else "(No dedicated hint from Judge for this stage — "
                  "use your own judgment)",
                  "Please adjust parameters accordingly and explain reasoning in 'reason'."]

        parts += ["\nJSON format:", self.schema_desc()]
        return "\n".join(parts)

    def schema_desc(self) -> str:
        fields = ", ".join(
            f'"{s.name}": <{s.ptype} {s.vmin}–{s.vmax}>' for s in self.specs)
        return '{"params": {' + fields + '}, "reason": "<brief justification>"}'

    def _fallback_params(self, context: Dict[str, Any]) -> Dict[str, Any]:
        best = context.get("global_best")
        if best:
            best_my = best.get("params", {}).get(self.stage)
            if best_my:
                return dict(best_my)
        return default_stage_params(self.stage)

    def validate(self, raw: Dict[str, Any],
                 context: Dict[str, Any]) -> Dict[str, Any]:
        params_in = raw.get("params")
        if not isinstance(params_in, dict):
            raise AgentOutputError(f"[{self.tag}] output missing 'params' dict")

        known_names = {s.name for s in self.specs}
        unknown = set(params_in) - known_names
        if unknown:
            log.warning("[%s] discarding unknown params: %s", self.tag, sorted(unknown))

        fallback = self._fallback_params(context)
        out: Dict[str, Any] = {}
        for spec in self.specs:
            if spec.name in params_in:
                try:
                    out[spec.name] = spec.cast(params_in[spec.name])
                    continue
                except (TypeError, ValueError):
                    log.warning("[%s] param %s=%r cannot convert, using fallback",
                                self.tag, spec.name, params_in[spec.name])
            if spec.name in fallback:
                out[spec.name] = fallback[spec.name]
        return {"params": out, "reason": str(raw.get("reason", "")).strip()}

    def act(self, context: Dict[str, Any]) -> Dict[str, Any]:
        try:
            return super().act(context)
        except (LLMError, AgentOutputError) as e:
            params = self._fallback_params(context)
            log.error("[%s] fallback (%s): reuse params %s", self.tag, e, params)
            return {"params": params, "reason": f"fallback: {e}"}


class FPAgent(StageAgent):
    stage = "FP"
    persona = ("A senior floorplan engineer skilled in trading off core utilization "
               "and aspect ratio among chip area, routability, and timing.")


class PLAgent(StageAgent):
    stage = "PL"
    persona = ("A senior standard cell placement engineer with deep understanding of "
               "how placement density margin and cell padding affect wirelength, "
               "congestion, and timing.")


class CTSAgent(StageAgent):
    stage = "CTS"
    persona = ("A senior clock tree synthesis (CTS) engineer, familiar with the "
               "trade-offs between sink cluster size/diameter and clock skew, "
               "insertion delay, buffer power, and the role of setup repair margin.")


class RTAgent(StageAgent):
    stage = "RT"
    persona = ("A senior routing engineer, familiar with how global routing layer "
               "capacity adjustment factor and congestion elimination iterations "
               "affect wirelength, DRC convergence, and timing.")


def build_stage_agents(llm: Any, cfg: FrameworkConfig) -> Dict[str, StageAgent]:
    return {"FP": FPAgent(llm, cfg), "PL": PLAgent(llm, cfg),
            "CTS": CTSAgent(llm, cfg), "RT": RTAgent(llm, cfg)}
