# -*- coding: utf-8 -*-
"""gwtw/orchestrator.py — Doomed/GWTW multi-agent orchestration entry.

Integrates JudgeAgent + FP/PL/CTS/RT StageAgents with the Doomed/GWTW
pipeline (cohort_executor, doomed_predictor, gwtw_scheduler, mutation_planner).

Pipeline:
  1. Bootstrap population: Judge + StageAgents generate per-candidate params,
     execute to PL checkpoint.
  2. PL cohort: DoomedPredictor → GWTWScheduler → fork/continue/pause/audit.
     When Agents are available, child params come from StageAgents instead of
     mutation_planner; parent selection validated against survivor whitelist.
  3. Advance survivors + children to CTS.
  4. CTS cohort: same as PL, with CTS/RT Agents for child params.
  5. Advance survivors + children to finish.
  6. Collect final QoR and trace evidence.

Pure Python — no ORFS, no network.  MockLLMClient + RecordingFakeRunner for
zero-token testing.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional

from config import FrameworkConfig
from storage.decision_trace import (
    DEFAULT_TRACE_PATH,
    DecisionTraceWriter,
)
from storage import CheckpointManager, TrialManager
from search.tree import OptimizationTree
from core.models import (
    TrialRecord,
)

log = logging.getLogger(__name__)

_DEFAULT_DOOMED_VERSION = "1.0.0"
_DEFAULT_SCHEDULER_VERSION = "1.0.0"
_DEFAULT_PLANNER_VERSION = "1.0.0"

_STAGE_ORDER = ["FP", "PL", "CTS", "RT", "finish"]
_CHECKPOINTABLE = {"FP", "PL", "CTS"}
_STAGE_NEXT: Dict[str, str] = {"FP": "PL", "PL": "CTS", "CTS": "RT"}
_STAGE_ARTIFACTS: Dict[str, List[str]] = {
    "FP":  ["2_floorplan.odb", "2_floorplan.sdc"],
    "PL":  ["3_place.odb", "3_place.sdc"],
    "CTS": ["4_cts.odb", "4_cts.sdc"],
    "RT":  ["5_route.odb", "5_route.sdc"],
}


# =============================================================================
# Config
# =============================================================================

from gwtw.config import MultiAgentGWTWConfig
from gwtw.proposals import AgentProposal, ParentSelectionRecord, StageEResult
from gwtw.fake_runner import StageERecordingFakeRunner, _resolve_trial_id
from gwtw.population import (
    _downstream_stages as _pop_downstream_stages,
    _enforce_child_parent_whitelist as _pop_enforce_whitelist,
    _generate_params_for_candidate as _pop_generate_params,
    _judge_select_parent as _pop_judge_select_parent,
    _select_and_validate_parent as _pop_select_parent,
    _write_agent_proposal_trace as _pop_write_proposal_trace,
    _bootstrap_one as _pop_bootstrap_one,
    _bootstrap_population as _pop_bootstrap_population,
    is_survivor as _pop_is_survivor,
    validate_parent_in_whitelist as _pop_validate_whitelist,
)
from gwtw.cohort_run import (
    _execute_cohort_with_agents as _cr_execute_cohort_agents,
    _find_trial_in_cohort as _cr_find_trial,
    _resolve_child_checkpoint as _cr_resolve_child_cp,
    _run_cohort as _cr_run_cohort,
)
from gwtw.execution import (
    _add_children_to_tree as _ex_add_children,
    _add_stage_node_to_tree as _ex_add_node,
    _advance_one as _ex_advance_one,
    _collect_active as _ex_collect_active,
    _collect_cts_trials as _ex_collect_cts,
    _collect_survivors as _ex_collect_survivors,
    _count_disk_trials as _ex_count_disk,
    _create_checkpoint as _ex_create_checkpoint,
    _enforce_budget as _ex_enforce_budget,
    _find_deepest_node as _ex_find_deepest,
    _has_pl_trials as _ex_has_pl,
    _load_tree as _ex_load_tree,
    _make_unique_nid as _ex_unique_nid,
    _reserve_child_budget as _ex_reserve_budget,
    _run_stages as _ex_run_stages,
    _run_to_finish as _ex_run_to_finish,
    _save_tree as _ex_save_tree,
    _tree_path as _ex_tree_path,
    _variant_for as _ex_variant_for,
)
class MultiAgentGWTWOrchestrator:
    """Judge + 4 StageAgents + Doomed/GWTW pipeline orchestrator.

    - Bootstrap: Judge + StageAgents generate per-candidate params.
    - PL/CTS cohort: Doomed/GWTW decisions via plan_cohort; child params
      optionally generated by StageAgents instead of mutation_planner.
    - Parent selection validated against survivor whitelist; hard-dead/pause
      nodes rejected with traceable fallback.
    - Real-LLM mode: all-fallback proposals cause run failure (non-zero exit).
    """

    _NODE_ID_SEQ = 0

    def __init__(
        self, cfg: MultiAgentGWTWConfig, trial_mgr: TrialManager,
        checkpoint_mgr: CheckpointManager, runner: Any,
        judge_agent: Any = None, stage_agents: Dict[str, Any] = None,
        tree: Optional[OptimizationTree] = None,
    ) -> None:
        self.cfg = cfg
        self.trial_mgr = trial_mgr
        self.checkpoint_mgr = checkpoint_mgr
        self.runner = runner
        self.judge_agent = judge_agent
        self.stage_agents = stage_agents or {}
        self._runs_dir = cfg.runs_dir or trial_mgr.runs_dir
        self._iteration = 0
        self._new_trials = 0
        self._disk_trials_before = self._count_disk_trials()
        self.tree = tree or self._load_tree()
        self._node_to_trial: Dict[str, str] = {}
        self._trace_writer = DecisionTraceWriter(
            self._runs_dir, DEFAULT_TRACE_PATH)
        self._agent_proposals: Dict[str, AgentProposal] = {}
        self._survivor_whitelist_pl: List[str] = []
        self._survivor_whitelist_cts: List[str] = []
        self._parent_selections: List[ParentSelectionRecord] = []
        # Parent-selection fallback errors (reported in real-LLM mode).
        self._parent_selection_errors: List[str] = []
        # Track whether any real (non-fallback) Agent proposal was produced.
        self._any_real_proposal: bool = False

    # ------------------------------------------------------------------
    # Public entry
    # ------------------------------------------------------------------

    def run(self) -> StageEResult:
        result = StageEResult(
            experiment_id=self.cfg.experiment_id, seed=self.cfg.seed,
            resumed=self._has_pl_trials())

        import time as _time
        _wall_start = _time.monotonic()

        # ---- Bootstrap population (Agent-generated params) ----
        pop_trials = self._bootstrap_population()
        result.total_trials = self._disk_trials_before + self._new_trials

        # ---- Real-LLM guard: any fallback proposal → error ----
        if self._is_real_llm and self._has_agents:
            bootstrap_fallbacks = [
                p for p in self._agent_proposals.values()
                if p.proposal_role == "bootstrap" and p.is_fallback]
            if bootstrap_fallbacks:
                result.errors.append(
                    f"real-LLM mode: {len(bootstrap_fallbacks)} bootstrap "
                    f"Agent proposals are fallback — Agent call(s) degraded")
            if bootstrap_fallbacks and all(
                p.is_fallback for p in self._agent_proposals.values()
                if p.proposal_role == "bootstrap"):
                result.agent_proposals = list(self._agent_proposals.values())
                return result

        # ---- PL cohort ----
        try:
            result.pl_cohort_result = self._run_cohort(
                pop_trials, "PL", *self.cfg._pl_cohort_cfg)
        except Exception as e:
            result.errors.append(f"PL cohort Agent failure: {e}")
            result.agent_proposals = list(self._agent_proposals.values())
            return result
        if result.pl_cohort_result is None:
            result.errors.append("PL cohort failed")
            result.agent_proposals = list(self._agent_proposals.values())
            return result

        self._survivor_whitelist_pl = self._collect_survivors(
            result.pl_cohort_result)
        result.survivor_whitelist_pl = list(self._survivor_whitelist_pl)

        # Real-LLM guard: check PL child proposals for fallback.
        if self._is_real_llm:
            pl_child_fallbacks = [
                cid for cid in result.pl_cohort_result.child_trial_ids
                if self._agent_proposals.get(cid, AgentProposal(
                    trial_id=cid, candidate_index=-1)).is_fallback]
            if pl_child_fallbacks:
                result.errors.append(
                    f"real-LLM: {len(pl_child_fallbacks)} PL children have "
                    f"fallback Agent proposals — Agent call(s) failed")

        # Enforce whitelist on all PL children created by the cohort.
        self._enforce_child_parent_whitelist(
            result.pl_cohort_result, "PL")

        active_pl = self._collect_active(result.pl_cohort_result)
        self._add_children_to_tree(result.pl_cohort_result)
        for t in active_pl:
            self._advance_one(t, "CTS")
        self._save_tree()

        cts_trials = self._collect_cts_trials(result.pl_cohort_result)

        # ---- CTS cohort ----
        try:
            result.cts_cohort_result = self._run_cohort(
                cts_trials, "CTS", *self.cfg._cts_cohort_cfg)
        except Exception as e:
            result.errors.append(f"CTS cohort Agent failure: {e}")
            result.agent_proposals = list(self._agent_proposals.values())
            result.survivor_whitelist_pl = list(self._survivor_whitelist_pl)
            return result
        if result.cts_cohort_result is None:
            result.errors.append("CTS cohort failed")
            result.agent_proposals = list(self._agent_proposals.values())
            result.survivor_whitelist_pl = list(self._survivor_whitelist_pl)
            return result

        self._survivor_whitelist_cts = self._collect_survivors(
            result.cts_cohort_result)
        result.survivor_whitelist_cts = list(self._survivor_whitelist_cts)

        # Real-LLM guard: check CTS child proposals for fallback.
        if self._is_real_llm:
            cts_child_fallbacks = [
                cid for cid in result.cts_cohort_result.child_trial_ids
                if self._agent_proposals.get(cid, AgentProposal(
                    trial_id=cid, candidate_index=-1)).is_fallback]
            if cts_child_fallbacks:
                result.errors.append(
                    f"real-LLM: {len(cts_child_fallbacks)} CTS children have "
                    f"fallback Agent proposals — Agent call(s) failed")

        self._enforce_child_parent_whitelist(
            result.cts_cohort_result, "CTS")

        active_cts = self._collect_active(result.cts_cohort_result)
        self._add_children_to_tree(result.cts_cohort_result)
        for t in active_cts:
            self._advance_one(t, "finish")
        self._save_tree()

        result.finish_trial_ids = [
            t.trial_id for t in active_cts
            if self.trial_mgr.get(t.trial_id)
            and self.trial_mgr.get(t.trial_id).status == "ok"]
        # Aggregate parent-selection errors (real-LLM mode only).
        if self._is_real_llm and self._parent_selection_errors:
            result.errors.extend(self._parent_selection_errors)
        result.total_trials = self._disk_trials_before + self._new_trials
        result.budget_remaining = self.cfg.max_trials - result.total_trials
        result.agent_proposals = list(self._agent_proposals.values())
        result.parent_selections = list(self._parent_selections)

        _wall_elapsed = _time.monotonic() - _wall_start
        if (self.cfg.wall_clock_budget_s is not None
                and _wall_elapsed > self.cfg.wall_clock_budget_s):
            result.errors.append(
                f"wall_clock_budget exceeded: "
                f"{_wall_elapsed:.1f}s > {self.cfg.wall_clock_budget_s}s")

        return result

    # ------------------------------------------------------------------
    # Real-LLM detection
    # ------------------------------------------------------------------

    @property
    def _is_real_llm(self) -> bool:
        """True when using a real LLM client (not MockLLMClient)."""
        if self.judge_agent is None:
            return False
        llm = getattr(self.judge_agent, "llm", None)
        if llm is None:
            return False
        from agents.llm import MockLLMClient
        return not isinstance(llm, MockLLMClient)

    @property
    def _has_agents(self) -> bool:
        return self.judge_agent is not None and bool(self.stage_agents)

    # ------------------------------------------------------------------
    # Bootstrap (Agent-generated parameters)
    # ------------------------------------------------------------------


    def _bootstrap_population(self, *a, **kw):
        return _pop_bootstrap_population(self, *a, **kw)
    def _bootstrap_one(self, *a, **kw):
        return _pop_bootstrap_one(self, *a, **kw)
    def _generate_params_for_candidate(self, *a, **kw):
        return _pop_generate_params(self, *a, **kw)
    def _write_agent_proposal_trace(self, *a, **kw):
        return _pop_write_proposal_trace(self, *a, **kw)
    def _judge_select_parent(self, *a, **kw):
        return _pop_judge_select_parent(self, *a, **kw)
    def _select_and_validate_parent(self, *a, **kw):
        return _pop_select_parent(self, *a, **kw)
    def validate_parent_in_whitelist(self, *a, **kw):
        return _pop_validate_whitelist(self, *a, **kw)
    def is_survivor(self, *a, **kw):
        return _pop_is_survivor(self, *a, **kw)
    def _enforce_child_parent_whitelist(self, *a, **kw):
        return _pop_enforce_whitelist(self, *a, **kw)
    def _run_cohort(self, *a, **kw):
        return _cr_run_cohort(self, *a, **kw)
    def _execute_cohort_with_agents(self, *a, **kw):
        return _cr_execute_cohort_agents(self, *a, **kw)
    def _resolve_child_checkpoint(self, *a, **kw):
        return _cr_resolve_child_cp(self, *a, **kw)
    @staticmethod
    def _find_trial_in_cohort(cohort, trial_id):
        return _cr_find_trial(cohort, trial_id)
    def _reserve_child_budget(self, *a, **kw):
        return _ex_reserve_budget(self, *a, **kw)
    def _enforce_budget(self, *a, **kw):
        return _ex_enforce_budget(self, *a, **kw)
    def _count_disk_trials(self, *a, **kw):
        return _ex_count_disk(self, *a, **kw)
    def _has_pl_trials(self, *a, **kw):
        return _ex_has_pl(self, *a, **kw)
    def _tree_path(self, *a, **kw):
        return _ex_tree_path(self, *a, **kw)
    def _load_tree(self, *a, **kw):
        return _ex_load_tree(self, *a, **kw)
    def _save_tree(self, *a, **kw):
        return _ex_save_tree(self, *a, **kw)
    def _make_unique_nid(self, *a, **kw):
        return _ex_unique_nid(self, *a, **kw)
    def _add_stage_node_to_tree(self, *a, **kw):
        return _ex_add_node(self, *a, **kw)
    def _add_children_to_tree(self, *a, **kw):
        return _ex_add_children(self, *a, **kw)
    def _find_deepest_node(self, *a, **kw):
        return _ex_find_deepest(self, *a, **kw)
    def _advance_one(self, *a, **kw):
        return _ex_advance_one(self, *a, **kw)
    def _run_stages(self, *a, **kw):
        return _ex_run_stages(self, *a, **kw)
    def _run_to_finish(self, *a, **kw):
        return _ex_run_to_finish(self, *a, **kw)
    def _collect_survivors(self, *a, **kw):
        return _ex_collect_survivors(self, *a, **kw)
    def _variant_for(self, *a, **kw):
        return _ex_variant_for(self, *a, **kw)
    def _create_checkpoint(self, *a, **kw):
        return _ex_create_checkpoint(self, *a, **kw)
    def _collect_active(self, *a, **kw):
        return _ex_collect_active(self, *a, **kw)
    def _collect_cts_trials(self, *a, **kw):
        return _ex_collect_cts(self, *a, **kw)
    @staticmethod
    def _downstream_stages(decision_stage: str):
        return _pop_downstream_stages(decision_stage)
