# -*- coding: utf-8 -*-
"""agents/observation.py — Observation Tool: tree + history -> adaptive summary."""
from __future__ import annotations
import logging
from typing import Any, Dict, List, Optional

import config
from agents.base import STAGE_CN

log = logging.getLogger("agents")

def compute_exploration_balance(tree, max_branch_count: int) -> Dict[str, int]:
    """E(n): number of times each branchable node was chosen as branch origin"""
    nodes = tree.branchable_nodes(max_branch_count)
    return {n.node_id: n.branch_count for n in nodes}


def compute_stage_bottleneck(history: List[Dict[str, Any]],
                              best_qor) -> Dict[str, float]:
    """B(s): difference between best observed intermediate ws (ps) per stage
    across non-failed history entries and the global best ws.

    difference = best_ws - stage_best_ws (positive = this stage is the bottleneck).
    Returns 0 if no data for a stage.
    """
    from core.utils import QoR
    scores: Dict[str, List[float]] = {s: [] for s in config.STAGES}
    for entry in history:
        if entry.get("status") != "ok":
            continue
        sq = entry.get("stage_qor", {})
        for stage in config.STAGES:
            sqs = sq.get(stage, {})
            for key, val in sqs.items():
                if key.endswith("_ws_ps"):
                    scores[stage].append(float(val))
    best_ws = best_qor.wns_ps if best_qor and best_qor.wns_ps is not None else 0.0
    result: Dict[str, float] = {}
    for stage in config.STAGES:
        vals = scores[stage]
        if not vals:
            result[stage] = 0.0
        else:
            result[stage] = round(best_ws - max(vals), 1)
    return result


def build_observation_summary(tree, history: List[Dict[str, Any]],
                               best_qor, max_branch_count: int) -> str:
    """Build the "adaptive summary" text block for the Judge.

    Contains:
    - Branchable node list (node_id / stage / E(n) / per-stage ws along path)
    - Per-stage bottleneck scores B(s)
    """
    parts = ["## Search State Summary (auto-generated by Observation Tool)"]

    # Branchable node table
    nodes = tree.branchable_nodes(max_branch_count)
    if nodes:
        parts += ["\n### Branchable Nodes (selecting one reuses Bef results, zero re-run cost)",
                  "| node_id | stage | E(n) | Path QoR (ws_ps) |",
                  "|---------|-------|------|-----------------|"]
        for n in nodes:
            path_qor = tree.get_path_qor_summary(n.node_id)
            qor_str = " → ".join(
                f"{s}:{ws:.0f}" if ws is not None else f"{s}:?" for s, ws in path_qor)
            parts.append(f"| {n.node_id} | {n.stage} | {n.branch_count} | {qor_str} |")
    else:
        parts += ["\n(No branchable nodes — this round must start from ROOT, full run from FP)"]

    # Stage bottleneck scores
    bottleneck = compute_stage_bottleneck(history, best_qor)
    parts += ["\n### Stage Bottleneck B(s) (ws gap vs. global best; larger positive = more bottlenecked)"]
    for stage in config.STAGES:
        parts.append(f"- {stage} ({STAGE_CN[stage]}): B={bottleneck[stage]:.1f} ps")
    if best_qor is not None and best_qor.wns_ps is not None:
        parts.append(f"\nGlobal best ws (reference baseline): {best_qor.wns_ps:.1f} ps")

    return "\n".join(parts)


# =========================================================================
# History serialization (shared by Judge and StageAgent)
# =========================================================================

def _format_params_inline(stage_params: Dict[str, Dict[str, Any]]) -> str:
    parts = []
    for stage in config.STAGES:
        params = stage_params.get(stage, {})
        inner = ",".join(f"{k}:{v}" for k, v in params.items())
        parts.append(f"{stage}{{{inner}}}")
    return " ".join(parts)


def _format_entry_line(entry: Dict[str, Any], is_best: bool) -> str:
    """Single history entry → one-line text (including branch info)"""
    it = entry.get("iteration")
    params_str = _format_params_inline(entry.get("params", {}))

    branch_info = ""
    bn = entry.get("branch_node")
    bs = entry.get("branch_stage")
    if bn and bs:
        # Show only meaningful fragments to avoid excessively long lines:
        # extract iter number and stage
        short_node = bn.split("_")[-2] + "_" + bn.split("_")[-1] if "_" in bn else bn
        branch_info = f", from {short_node}@{bs}"

    if entry.get("status") == "ok" and entry.get("qor"):
        from core.utils import QoR
        qor = QoR.from_dict(entry["qor"])
        status_str = "[ok" + branch_info + "]"
        qor_str = qor.pretty() if qor else "QoR=N/A"
    else:
        failed_stage = entry.get("failed_stage") or "unknown"
        status_str = f"[FAILED@{failed_stage}{branch_info}]"
        qor_str = "QoR=N/A"

    line = f"#{it} {status_str} {params_str} | {qor_str}"

    decision = entry.get("judge_decision")
    if decision:
        bs_short = decision.get("branch_stage", "")
        hint = (decision.get("hints", {}).get(bs_short) or
                decision.get("hint") or "")[:50]
        line += f" | judge:{bs_short} \"{hint}\""
    if is_best:
        line += "  *BEST*"
    return line


def format_history(history: List[Dict[str, Any]], window: int,
                   best_iteration: Optional[int]) -> str:
    """Serialize optimization history: take most recent `window` entries,
    always including the best entry (marked *BEST*)"""
    if not history:
        return "(No history yet)"

    recent = history[-window:]
    lines: List[str] = []
    recent_iters = {e.get("iteration") for e in recent}
    if best_iteration is not None and best_iteration not in recent_iters:
        best_entry = next((e for e in history
                           if e.get("iteration") == best_iteration), None)
        if best_entry:
            lines.append(_format_entry_line(best_entry, is_best=True))
            lines.append("...")
    for entry in recent:
        lines.append(_format_entry_line(
            entry, is_best=(entry.get("iteration") == best_iteration)))
    return "\n".join(lines)


def render_param_table(stage: str) -> str:
    lines = []
    for spec in config.PARAM_SPACE[stage]:
        rng = (f"{int(spec.vmin)}–{int(spec.vmax)}" if spec.ptype == "int"
               else f"{spec.vmin}–{spec.vmax}")
        base = "baseline unset" if spec.default is None else f"baseline={spec.default}"
        lines.append(f"- {spec.name} ({spec.ptype}, range {rng}, {base}): {spec.description}")
    return "\n".join(lines)


def default_stage_params(stage: str) -> Dict[str, Any]:
    params = dict(config.BASELINE_PARAMS.get(stage, {}))
    for spec in config.PARAM_SPACE[stage]:
        if spec.name not in params and spec.default is not None:
            params[spec.name] = spec.default
    return params


# =========================================================================
# Agent base class
# =========================================================================

